export function makeGameView(overrides: Record<string, unknown> = {}): any {
  const base = {
    public: {
      game_id: "game-1",
      day: 1,
      phase: "DAY_DISCUSSION",
      mock_ai: true,
      players: [
        {
          id: "human",
          name: "旅人",
          seat: 0,
          is_human: true,
          alive: true,
          ghost_vote_available: true,
          nominated_today: false,
          was_nominated_today: false,
        },
        {
          id: "ai_1",
          name: "林鏡",
          seat: 1,
          is_human: false,
          alive: true,
          ghost_vote_available: true,
          nominated_today: false,
          was_nominated_today: false,
        },
        {
          id: "ai_2",
          name: "周棠",
          seat: 2,
          is_human: false,
          alive: false,
          ghost_vote_available: false,
          nominated_today: false,
          was_nominated_today: false,
        },
        {
          id: "ai_3",
          name: "沈炬",
          seat: 3,
          is_human: false,
          alive: true,
          ghost_vote_available: true,
          nominated_today: false,
          was_nominated_today: false,
        },
        {
          id: "ai_4",
          name: "許霜",
          seat: 4,
          is_human: false,
          alive: true,
          ghost_vote_available: true,
          nominated_today: false,
          was_nominated_today: false,
        },
        {
          id: "ai_5",
          name: "祁風",
          seat: 5,
          is_human: false,
          alive: true,
          ghost_vote_available: true,
          nominated_today: false,
          was_nominated_today: false,
        },
      ],
      public_events: [
        {
          id: "pub-1",
          day: 1,
          phase: "DAY_DISCUSSION",
          scope: "PUBLIC",
          message: "公開訊息",
          type: "public_speech",
          target_ids: [],
          participants: [],
        },
      ],
      nominations: [],
      votes: [],
      last_night_deaths: [],
      current_on_the_block: null,
      current_high_votes: 0,
      result: null,
      ai_status: "AI 自主行動每 5 秒檢查一次。",
      ai_active_player_id: null,
      ai_cooldown_seconds: 5,
      discussion_rounds_today: 0,
      usage: {
        calls: 3,
        input_tokens: 100,
        output_tokens: 40,
        reasoning_tokens: 0,
        estimated_usd: 0,
        budget_usd: 1,
        remaining_usd: 1,
        by_player: {},
        by_purpose: {},
        estimate_note: "費用為本機估算",
      },
    },
    private: {
      player_id: "human",
      name: "旅人",
      seat: 0,
      alive: true,
      ghost_vote_available: true,
      role: {
        slug: "artist",
        zh_name: "藝術家",
        role_type: "鎮民",
        ability: "每局一次詢問是非問題。",
      },
      apparent_alignment: "good",
      private_events: [
        {
          id: "priv-1",
          day: 1,
          phase: "FIRST_NIGHT",
          scope: "PLAYER_ONLY",
          message: "你的角色是 藝術家。",
          type: "role_info",
          target_ids: ["human"],
          participants: [],
        },
      ],
      private_chats: [
        {
          id: "chat-1",
          day: 1,
          phase: "PRIVATE_CHAT",
          scope: "PRIVATE_CHAT_PARTICIPANTS",
          message: "旅人 私下對 林鏡 說：你好",
          type: "private_chat",
          target_ids: ["ai_1"],
          participants: ["human", "ai_1"],
        },
      ],
      legal_actions: ["artist_question", "nominate"],
    },
    script: [
      {
        slug: "artist",
        zh_name: "藝術家",
        role_type: "鎮民",
        ability: "每局一次詢問是非問題。",
      },
      {
        slug: "imp",
        zh_name: "小惡魔",
        role_type: "惡魔",
        ability: "每晚攻擊。",
      },
    ],
    postgame: null,
    dev_reveal: null,
    session_token: "test-token",
  };
  return { ...base, ...overrides };
}
